@url_dev=http://127.0.0.1:3001/v1/api

//signup

POST {{{{url_dev}}}}/shop/signup
Content-Type: application/json

{
    "name":"Lethang Shop",
    "email": "cbst96@gmail.com",
    "password":"lethang321"
}